# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "12200bc9c46b6ddc21acbd8862d26d41c0e3302492f500ad70e9fd0421fc965e4e41";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/musl-fts.zig/archive/5a357938abd1ed4432130ac47a8a2c12eb424345.tar.gz";
      hash = "sha256-iCTk+av+NRAFQOns79NSVgnwnvvFAEgCiyNb8g0xYZ4=";
    };
  }
  {
    name = "12202eb14542007cd097b12fec91994575c89fff4177fc126ebf1240e9758dc758a4";
    path = fetchzip {
      url = "https://github.com/ExpidusOS/pkgbuild/archive/18ced610bf2e0fd102b45ecd885c683fd504e312.tar.gz";
      hash = "sha256-2wrHP2G8Z7vg9n9lq7RRK8H4o90imLOG2T26nGH09VE=";
    };
  }
  {
    name = "12202fa30d679d821292bcd953458b9e76097a5d16999489125a206db63a53392833";
    path = fetchzip {
      url = "https://github.com/Hejsil/zig-clap/archive/4267b0b60ef6f87cccf3ee6ed481e6d0759180c6.tar.gz";
      hash = "sha256-Wyti3pqEHFoHgD+Iny+O5S2ipe4e2Q1F/957vCKyCbU=";
    };
  }
  {
    name = "1220373131b333523a0f8515e8c1e121e19cf8c4e03a7dda36901782d76cb9376a5c";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/expat.zig/archive/24b51902a3fb8b9703dd1a629b51a25226a06e41.tar.gz";
      hash = "sha256-dBFEIrR7pc71c+swXxThRpiQ22ma6eOseQaCXQSm3Go=";
    };
  }
  {
    name = "12203b6e6ec7bb3b967233de8bd51524a16be5e9180dba53160c487394619cfb7626";
    path = fetchzip {
      url = "https://github.com/libexpat/libexpat/releases/download/R_2_6_0/expat-2.6.0.tar.gz";
      hash = "sha256-mEKaLL/re+jqqbZZ6+ATtjl3Gi2lqE+npXVr0Xj2D0E=";
    };
  }
  {
    name = "1220446fb3c59fba75208d22155bd212ea49c4cd6b7c1307f360c89138d913cd8035";
    path = fetchzip {
      url = "https://github.com/SELinuxProject/selinux/releases/download/3.6/libselinux-3.6.tar.gz";
      hash = "sha256-Uc0DzsMyJFieJgN6V7S1jFrgG43Pf3TKraMfJCHZQt0=";
    };
  }
  {
    name = "1220470e48999989b87360b808d5617d491278e9b9d4a6fd96d1ee1f183577dd5dac";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/libcap-ng.zig/archive/4f7e4294472368d1cd9bd9a14c65c824e740503d.tar.gz";
      hash = "sha256-ZqTSssMiwXi4U2nFQq9rvAepIy+Azh3uIXzydqTXi5Y=";
    };
  }
  {
    name = "12204c14e6f4e3481b16dd1482f1d94285ec3154a65701b767a2c062f80f62f86ce4";
    path = fetchzip {
      url = "https://gitlab.com/apparmor/apparmor/-/archive/v3.1.7/apparmor-v3.1.7.tar.gz";
      hash = "sha256-AzY05bcpNYXix2GL4Rhc9d3RBA1pd2fwOa7yoiwc2nQ=";
    };
  }
  {
    name = "1220500af520622a629c3e424ca786880361f6ad229078f6ce5f4905c8d2d2d8effb";
    path = fetchzip {
      url = "https://github.com/PCRE2Project/pcre2/archive/589fea34c87a43d5d6521b3bc3f890f00aaa557b.tar.gz";
      hash = "sha256-pbCskVuW9cxFYKPlR4wpsL0CFIqegDrz7mUzl/4f9PQ=";
    };
  }
  {
    name = "12205f2bf69294216864d8ced53358d2ea3e7dfda7c586581df65d6a8ab3fcb3e23d";
    path = fetchzip {
      url = "https://dbus.freedesktop.org/releases/dbus/dbus-1.14.10.tar.xz";
      hash = "sha256-jzFlw+0PWuRaND4s4rBY1F2xWwU8wqCE1omYPVDusQs=";
    };
  }
  {
    name = "1220662abc88111ae6702cea73c00f9a9adfef0fd8ded755c5e69bf83a1f60a74fed";
    path = fetchzip {
      url = "https://nongnu.askapache.com/attr/attr-2.5.2.tar.gz";
      hash = "sha256-4hHkztTZoVE9MzWwbnp1WS96ft8gTDUwvRaiSyY+3Dk=";
    };
  }
  {
    name = "12206ae9ce0671d93054f82524b04098439fbee8f3a906732acc9aaa2acff5206e4c";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/attr.zig/archive/475154966e342d69a91d78f600beb2136315c3e8.tar.gz";
      hash = "sha256-qgtziovTO6Tj7o6LyJzeKvVO213/AIdsNQZHTfAbkq8=";
    };
  }
  {
    name = "122075bf1b680cb1fd8550740578ca47e3e08328cca1532bcc38f5854e390e030f26";
    path = fetchzip {
      url = "https://github.com/ExpidusOS/pkgbuild/archive/1040e6f74b6b6a79639876f6b02b9f40775d2303.tar.gz";
      hash = "sha256-x4culfJGhuynlUbje79Mv0ig3sujwVW+1JsnHT+sjqs=";
    };
  }
  {
    name = "122077c813b5bcc473f67be4978f2730ca201cc6f13b0a26aa5a05265676bccc9a3e";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/apparmor.zig/archive/6c694a3080d8ff15045ff0d2e8686710dfddb759.tar.gz";
      hash = "sha256-ZEPUD8peaeaUF9h2QQklQIC6MfyhC+wljoYDhbQTYYc=";
    };
  }
  {
    name = "12207a76b79a7399a3937c1d5f67b00f85b360086f83e5f032a7525912d15f4e5910";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/cpython/archive/5fcfcab85bdef583263126ab98d49921c812ec15.tar.gz";
      hash = "sha256-yuhG9g30b+aOePUXjd7FMC0JmpaCO0X/1qbX6lPijHE=";
    };
  }
  {
    name = "122091abe3a043760a355ad8dd0d17bceade6a5352dbbc671f34f5986b95c8dacf84";
    path = fetchzip {
      url = "http://smarden.org/runit/runit-2.1.2.tar.gz";
      hash = "sha256-nnsvm9aafvYeiOu5TVdudmffu0azvmFw2f7IdWHDAqg=";
    };
  }
  {
    name = "12209af9de10cb22a37b3d26c01e467bc0086c569837b34b35048e0975ed701ad2fe";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/libaudit.zig/archive/1e0f394fba48db1635fa18e3d46164970c556e83.tar.gz";
      hash = "sha256-L8HL1Qmv0kKuRbklqjrVMEr5UCnyzTRuQma+nfyILVE=";
    };
  }
  {
    name = "1220a06039f203b43526577b3c6fdfebd78a37ec3535e01adee3dc8334a5a4a27f85";
    path = fetchzip {
      url = "https://people.redhat.com/sgrubb/libcap-ng/libcap-ng-0.8.4.tar.gz";
      hash = "sha256-hvkk1jQwyw8MQe5vC78Q6704ZOVhLtsXH2TYn4Sooes=";
    };
  }
  {
    name = "1220b1d1c438cfdf381a5439ed9744c568d4bcf2242bc21232c8e73db451ab1f5562";
    path = fetchzip {
      url = "https://nongnu.askapache.com/acl/acl-2.3.2.tar.gz";
      hash = "sha256-bd69t6ix9j5FqqM8Wzp8DulYOChZJSxWPiciQkbIOXc=";
    };
  }
  {
    name = "1220c5a736dd635e70e3132d5e87f8c7ec22626c4b98a6c00672c3d55448653a0993";
    path = fetchzip {
      url = "https://people.redhat.com/sgrubb/audit/audit-4.0.tar.gz";
      hash = "sha256-L9PwYJUZbezlQXr0GJi78RADWyUpvmKkAqUqhXNKn3M=";
    };
  }
  {
    name = "1220cc326574f724d468f397b7c0eebb29c143c37cfb55b0a8ff8a3f608050bab9c0";
    path = fetchzip {
      url = "https://github.com/void-linux/musl-fts/archive/refs/tags/v1.2.7.tar.gz";
      hash = "sha256-Azw5qrz6OKDcpYydE6jXzVxSM5A8oYWAztrHr+O/DOE=";
    };
  }
  {
    name = "1220cd6e19dc1bf38fbbd5bdbfe0344bbb84323afa5521294262be98276acdf44b45";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/python.zig/archive/e30fade3dce443f110399b9e04f867eb3b7df364.tar.gz";
      hash = "sha256-u51vIdRUcYamozaCSsxwflnSpwXZvEJzPQ5EEIar67o=";
    };
  }
  {
    name = "1220dd7f498996da2483865cb7c4dbe12e465239fd22501e4d9e58041f6b2705edd5";
    path = fetchzip {
      url = "https://github.com/SELinuxProject/selinux/releases/download/3.6/libsepol-3.6.tar.gz";
      hash = "sha256-qr3CPNca/P/FkaWMsqNhNiigABjKKQx5vmglyCbFoM8=";
    };
  }
  {
    name = "1220e1dea1b8b34378a88c991166cd3941fc0f77bbc19fbbf8dbeb34c91d88ba39c8";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/libcap-ng.zig/archive/a754e5adc8ae4f0b8ec25a481dd07250d445ba57.tar.gz";
      hash = "sha256-JuPUuYMghPPaY8A+tiMRXIkzO0teNc6ieRngHDyVj1k=";
    };
  }
  {
    name = "1220e2e014950973314e9bcee7375ea5248270d4f5761d39d3db3760d20a351d599a";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/ziggybox/archive/b56774a0097b33181fe9707e5bfb62d047bcbfa1.tar.gz";
      hash = "sha256-NB0QgiOywctpY49610WkMw5JLWv/apnjf20giQWLSIQ=";
    };
  }
  {
    name = "1220ee07f7563df59f3a1db7bb74498c44318e7eedd0abff05a20fa786bd03b6de74";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/selinux.zig/archive/8f70d59c6f1239e165ade8d46c679124b1cced69.tar.gz";
      hash = "sha256-+sHAf+UdHgA0xJ/s7Qyv+OpBa8ZX7HyOdm/29M1izCY=";
    };
  }
  {
    name = "1220efd95ebce30c67d1acb1b7769da37223ba4610c3ed7df7cb5238a1c0ac19cdbf";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/dbus.zig/archive/f1de41f5d1cd1b666189f5cb08249e80fbe83d78.tar.gz";
      hash = "sha256-7KvfsD2wvlsnr35VC0nXMoxc1/TC1e2KOFFsg9ohY74=";
    };
  }
  {
    name = "1220f16070c01a83dadefe5ee9a983c5908bd418e36e0f17fbf97e8315d028897f8f";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/acl.zig/archive/dcdaccaeb281f82c7715f17f8250cc7d01c475a5.tar.gz";
      hash = "sha256-jSiGL0Ko1m3Uvx/EJ4Lm23AQKbcBMbd7eqKK8mSNaOo=";
    };
  }
  {
    name = "1220f401289c2aff8eb83d18fe4e3626d0ad7c6899960d50b07ed9da4f14288811c3";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/runit.zig/archive/1707804e08e44f8865b53c767489b807ff746406.tar.gz";
      hash = "sha256-nXe4nlJGz7Wc1itPgCCB5EnGTaLNSCYrzalu+kLsZTU=";
    };
  }
  {
    name = "1220fe80f8f80b02213a1aa25d000f65fc889e8f8e39d0a0344a35caaef9c1b35bb7";
    path = fetchzip {
      url = "https://github.com/ExpidusOS/build/archive/aab78d6bd30004e002361dc5e66c090719bb88a7.tar.gz";
      hash = "sha256-yDRQ2ZPqYHKFNaWN32PISZiorObMMWAniky4+N5VunA=";
    };
  }
]
