# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "12200103e7b4a0cb162f2912df4fe97914024a25b5c9fcce6ea4119744f3f2a7f24e";
    path = fetchzip {
      url = "https://github.com/Hejsil/zig-clap/archive/209ba4da76e46412acfe18f711cb0b041ff37f10.tar.gz";
      hash = "sha256-6oHwQ591KkvlDtkeX2srJKRawx+eA03OnGg3E3GCNrI=";
    };
  }
  {
    name = "12200a06fb7904e5c889fb166d308a2bfb68fb6ccdc935ab8aaa391f8c1f7616bc2d";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/libaudit.zig/archive/fb23cb4cf69b2dd6b1bca09b7bfa8106db90c044.tar.gz";
      hash = "sha256-HV7LEv9/Ja4TTR5PC46iK08YYhDULHwhvKPsfSiCqJA=";
    };
  }
  {
    name = "122014e187ac96e85a93e24ec7663bfc7a844fb6b813a448173a74e9cb069a9067ff";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/apparmor.zig/archive/cf38b107e6f4b82b35466233473d1a98a16601c9.tar.gz";
      hash = "sha256-ZaVI8zm97c4Aj4z1iqY/1r1Ca+LcFy9KTyHsTYLTtkU=";
    };
  }
  {
    name = "12202eb14542007cd097b12fec91994575c89fff4177fc126ebf1240e9758dc758a4";
    path = fetchzip {
      url = "https://github.com/ExpidusOS/pkgbuild/archive/18ced610bf2e0fd102b45ecd885c683fd504e312.tar.gz";
      hash = "sha256-2wrHP2G8Z7vg9n9lq7RRK8H4o90imLOG2T26nGH09VE=";
    };
  }
  {
    name = "12203b6e6ec7bb3b967233de8bd51524a16be5e9180dba53160c487394619cfb7626";
    path = fetchzip {
      url = "https://github.com/libexpat/libexpat/releases/download/R_2_6_0/expat-2.6.0.tar.gz";
      hash = "sha256-mEKaLL/re+jqqbZZ6+ATtjl3Gi2lqE+npXVr0Xj2D0E=";
    };
  }
  {
    name = "1220405f67f78da335345bbea315ab6bab96e0f23a4c63da11852a18929113613ff7";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/libcap-ng.zig/archive/3b9b2a81d817bc2e579d10a8e61327bc5c322346.tar.gz";
      hash = "sha256-BQJ6XuaQQHBaQOdmQuHWvcVkc/n60c1cerjVH1Z1Hg4=";
    };
  }
  {
    name = "1220446fb3c59fba75208d22155bd212ea49c4cd6b7c1307f360c89138d913cd8035";
    path = fetchzip {
      url = "https://github.com/SELinuxProject/selinux/releases/download/3.6/libselinux-3.6.tar.gz";
      hash = "sha256-Uc0DzsMyJFieJgN6V7S1jFrgG43Pf3TKraMfJCHZQt0=";
    };
  }
  {
    name = "12204c14e6f4e3481b16dd1482f1d94285ec3154a65701b767a2c062f80f62f86ce4";
    path = fetchzip {
      url = "https://gitlab.com/apparmor/apparmor/-/archive/v3.1.7/apparmor-v3.1.7.tar.gz";
      hash = "sha256-AzY05bcpNYXix2GL4Rhc9d3RBA1pd2fwOa7yoiwc2nQ=";
    };
  }
  {
    name = "12205c9afeae4b6fc701c05ea788f720af4b299c0b4c60e82cdf3a6c15c5f8a5f17b";
    path = fetchzip {
      url = "https://github.com/PCRE2Project/pcre2/archive/3c5ca5c1eabf64e1e0912b6c9eaa18850d4c3b40.tar.gz";
      hash = "sha256-RlEcNcu7nv4q/Sk9OtbboWmZvhiWfKsIyDYooKG5SGI=";
    };
  }
  {
    name = "12205f2bf69294216864d8ced53358d2ea3e7dfda7c586581df65d6a8ab3fcb3e23d";
    path = fetchzip {
      url = "https://dbus.freedesktop.org/releases/dbus/dbus-1.14.10.tar.xz";
      hash = "sha256-jzFlw+0PWuRaND4s4rBY1F2xWwU8wqCE1omYPVDusQs=";
    };
  }
  {
    name = "122061e4a254b14ccb92aa3047cdb08bab8440b177cb4e4a89a5ae10de621074638d";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/dbus.zig/archive/612d62bab8cc7a6231e9d619cf279b253ba369bb.tar.gz";
      hash = "sha256-v8nAGI/+QJAL9nIWLLOw6jGPVvgLwrD6H89e4b3Uf0k=";
    };
  }
  {
    name = "1220662abc88111ae6702cea73c00f9a9adfef0fd8ded755c5e69bf83a1f60a74fed";
    path = fetchzip {
      url = "https://nongnu.askapache.com/attr/attr-2.5.2.tar.gz";
      hash = "sha256-4hHkztTZoVE9MzWwbnp1WS96ft8gTDUwvRaiSyY+3Dk=";
    };
  }
  {
    name = "122068333e288a0fc27813c2335aa8e2d66c37602737f572ec803f29fb7f26375ca1";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/expat.zig/archive/0b908b69f347b50a25faa29b54dd5557f050c01c.tar.gz";
      hash = "sha256-YtRV8eR5MTBS7+tzy7XNk/J0PnAbWf4691zkcLHpDJU=";
    };
  }
  {
    name = "12207490f36e8d92099ce7dce1c7076b53c02bd1f06e09c59f2531e78fbf168d73ae";
    path = fetchzip {
      url = "https://github.com/eudev-project/eudev/releases/download/v3.2.14/eudev-3.2.14.tar.gz";
      hash = "sha256-vpyV3vgwb24+NyOMhK+SVbXFM/E7mswwsXxiiFCboJo=";
    };
  }
  {
    name = "12207a76b79a7399a3937c1d5f67b00f85b360086f83e5f032a7525912d15f4e5910";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/cpython/archive/5fcfcab85bdef583263126ab98d49921c812ec15.tar.gz";
      hash = "sha256-yuhG9g30b+aOePUXjd7FMC0JmpaCO0X/1qbX6lPijHE=";
    };
  }
  {
    name = "1220839da3e6999de970a44384724053d198657c638eb23e640e356b91c2640bea0f";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/python.zig/archive/42008343b427e049f67e5ccfdfafa9ccfb9377a5.tar.gz";
      hash = "sha256-AH08P00auzef8SzV9HACJywhoGRsQhMbk41L//Rkrsg=";
    };
  }
  {
    name = "12208465fb9d7358265b0c9d9cd403ba77c7c6a6b0f57e48e418f2674faaf85a6a5c";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/attr.zig/archive/429b487f620ebc9110112310ee5cd601359fa08a.tar.gz";
      hash = "sha256-tBOVJOIgmbpIWTt1crVw0DKwzI93j+6Ieu5d4Bpg+U0=";
    };
  }
  {
    name = "122091abe3a043760a355ad8dd0d17bceade6a5352dbbc671f34f5986b95c8dacf84";
    path = fetchzip {
      url = "http://smarden.org/runit/runit-2.1.2.tar.gz";
      hash = "sha256-nnsvm9aafvYeiOu5TVdudmffu0azvmFw2f7IdWHDAqg=";
    };
  }
  {
    name = "1220a06039f203b43526577b3c6fdfebd78a37ec3535e01adee3dc8334a5a4a27f85";
    path = fetchzip {
      url = "https://people.redhat.com/sgrubb/libcap-ng/libcap-ng-0.8.4.tar.gz";
      hash = "sha256-hvkk1jQwyw8MQe5vC78Q6704ZOVhLtsXH2TYn4Sooes=";
    };
  }
  {
    name = "1220a744681704d2f2f6567dd8fac006386045db7feaf9b5ff93710104a53d21f4e0";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/acl.zig/archive/ab887f24096a8597aefe46fae184d268bdb9c4b1.tar.gz";
      hash = "sha256-oJLKq/dQqVTs+j0azfSAyWAavZxnRKC5oLG3X5nUpNc=";
    };
  }
  {
    name = "1220b1d1c438cfdf381a5439ed9744c568d4bcf2242bc21232c8e73db451ab1f5562";
    path = fetchzip {
      url = "https://nongnu.askapache.com/acl/acl-2.3.2.tar.gz";
      hash = "sha256-bd69t6ix9j5FqqM8Wzp8DulYOChZJSxWPiciQkbIOXc=";
    };
  }
  {
    name = "1220bd0e542ac0c2e134727ba14b3f6917c3bd72b353018e2c86cd53a7aaa41164cc";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/selinux.zig/archive/1e98d94f24c404739004a8c1cbe43c49e7a926b0.tar.gz";
      hash = "sha256-h7crPBuC7mQOQ7Kf4GlG7a2RCXWJFyXAPw7CQw4LU1s=";
    };
  }
  {
    name = "1220bd52f38ea561f1fb8fde8a4531d6df55a32ad3424c5c7bd7d4ed2a10375f1611";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/musl-fts.zig/archive/7f7c861ec97e57bb5c73359cb277cde207efa6f9.tar.gz";
      hash = "sha256-oXwXnFgeu3g34jk1ZCDhsOOOtsvQMXYDeOFSupb8eLE=";
    };
  }
  {
    name = "1220c5a736dd635e70e3132d5e87f8c7ec22626c4b98a6c00672c3d55448653a0993";
    path = fetchzip {
      url = "https://people.redhat.com/sgrubb/audit/audit-4.0.tar.gz";
      hash = "sha256-L9PwYJUZbezlQXr0GJi78RADWyUpvmKkAqUqhXNKn3M=";
    };
  }
  {
    name = "1220c7bad4620ef36b42d29e3c45d0729ee87c123d0336add17fed773df9802acf0c";
    path = fetchzip {
      url = "https://gitlab.midstall.com/ExpidusOS/pkgs/c3/runit/-/archive/68e20e8063ee05bece23f66a4c7cbab5077e98f3/runit-68e20e8063ee05bece23f66a4c7cbab5077e98f3.tar.gz";
      hash = "sha256-nTWVS9zVYgAYhwrr8yFAsk7cMQSe+pHFTPmdIR5St8c=";
    };
  }
  {
    name = "1220cc326574f724d468f397b7c0eebb29c143c37cfb55b0a8ff8a3f608050bab9c0";
    path = fetchzip {
      url = "https://github.com/void-linux/musl-fts/archive/refs/tags/v1.2.7.tar.gz";
      hash = "sha256-Azw5qrz6OKDcpYydE6jXzVxSM5A8oYWAztrHr+O/DOE=";
    };
  }
  {
    name = "1220dd7f498996da2483865cb7c4dbe12e465239fd22501e4d9e58041f6b2705edd5";
    path = fetchzip {
      url = "https://github.com/SELinuxProject/selinux/releases/download/3.6/libsepol-3.6.tar.gz";
      hash = "sha256-qr3CPNca/P/FkaWMsqNhNiigABjKKQx5vmglyCbFoM8=";
    };
  }
  {
    name = "1220f7bce5b93295c1dcb0e50ce5576280bdd59ac1899b901b741139a92fbe25e0d8";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/eudev.zig/archive/1ff513d5db65db8e212522874cc7312929cb4ee8.tar.gz";
      hash = "sha256-SnleygdDWnLK3DDNe1ExVBMNFZW1smxvxdIDmy8YuWU=";
    };
  }
  {
    name = "1220fbae16cdf58be8f93d0271271e4be8b734a332cf9ba7f87a8558d4ffe0afd5d7";
    path = fetchzip {
      url = "https://github.com/MidstallSoftware/ziggybox/archive/be469a656d19c8ceeee9001482bde89fa3575432.tar.gz";
      hash = "sha256-O94nPxVJncEwH9okYl/h5xZHa98Egcj0ei/11lOakYE=";
    };
  }
  {
    name = "1220fe80f8f80b02213a1aa25d000f65fc889e8f8e39d0a0344a35caaef9c1b35bb7";
    path = fetchzip {
      url = "https://github.com/ExpidusOS/build/archive/aab78d6bd30004e002361dc5e66c090719bb88a7.tar.gz";
      hash = "sha256-yDRQ2ZPqYHKFNaWN32PISZiorObMMWAniky4+N5VunA=";
    };
  }
]
